[project]
name = "jubilant-sniffle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.23.0",
    "aiohttp>=3.13.2",
    "pydantic-settings>=2.12.0",
    "structlog>=25.5.0",
]
